= Solidity Loader

Solidity Hot Loader is a webpack loader that watches the smart contract `.sol` files you’re using. Once there’s a change, it compiles them, updates the local blockchain using the xref:upgrades::index.adoc[*OpenZeppelin Upgrades*], and refreshes your app in the browser while preserving your blockchain state.

The existing (slow) Solidity development cycle:

1.  Make a change to your smart contract `.sol` file and save it.
2.  Compile your contract.
3.  Deploy your contract.
4.  Restore the state.
5.  Restart dapp to get new contract.

The Solidity Hot Loader development cycle:

1.  Make a change to your smart contract `.sol` file and save it.
2.  Wait a bit.
3.  Done.

== Overview

=== Installation

[source,console]
----
$ npm install @openzeppelin/solidity-loader json-loader
----

=== Usage

Add the following https://webpack.js.org/configuration/module/#rule[rule] into your webpack configuration:
[source,javascript]
----
solidityLoader: {
  test: /\.sol$/,
  use: [
    { loader: 'json-loader' },
    {
      loader: '@openzeppelin/solidity-loader',
      options: {
        network: 'development',
        disabled: false,
      }
    },
  ],
}
----

NOTE: If you are using `create-react-app`, you may need to either eject the application to modify the webpack configuration, or use https://github.com/timarney/react-app-rewired[`react-app-rewired`].

Import your Solidity contracts into JavaScript like this:
[source,javascript]
----
counterJSON = require('../../contracts/Counter.sol');
----

Changes to your contracts in development will now hot load! ✨

== Learn More

 * Check out xref:getting-started.adoc[Getting Started] if you're new to the Solidity Loader
 * Watch our Devcon V https://youtu.be/KU6_r3sJ2E4[Delightful Developer Experience] presentation, by Igor Yalovoy.
 * For a step-by-step guide, head to xref:dapp.adoc[Building a Dapp with Solidity Hot Loader].
