= Solidity Loader

 * Allows importing `.sol` files directly into source code.
 * Allows specifying the contract name for `.sol` files, like `require("Contract.sol?contract=Counter")`.
 * Tracks dependencies for contracts, so children are updated when parents are modified.
 * Converts `.sol` files into `.json` using `oz compile` and `oz update`.
 * Uses the `development` network only, so won't run on any other networks.
 * Set the development network name using the loader's config.
 * Handles race conditions at Webpack pipeline using a lock.
 * Pulls build directory from config.
 * In case `openzeppelin` commands are not available, uses cached versions of `.json` files.
 * Reports errors to console output and dev tools.
 * Compilation can be disabled using the loader's disabled config.

== Overview

Solidity Hot Loader is a webpack loader that watches the smart contract `.sol` files you’re using. Once there’s a change, it compiles them, updates the local blockchain using the https://openzeppelin.com/sdk/[OpenZeppelin SDK], and refreshes your app in the browser while preserving your blockchain state. Compare this against the existing Solidity development cycle.

The Solidity Hot Loader development cycle:

1.  Make a change to your smart contract `.sol` file and save it.
2.  Wait a bit.
3.  Done.

The existing (slow) Solidity development cycle:

1.  Make a change to your smart contract `.sol` file and save it.
2.  Compile your contract.
3.  Deploy your contract.
4.  Restore the state.
5.  Restart dapp to get new contract.

=== Installation

[source,console]
----
$ npm install @openzeppelin/solidity-loader
----

=== Usage

Webpack configuration for Solidity Hot Loader:
[source,javascript]
----
solidityLoader: {
  test: /\.sol$/,
  use: [
    { loader: 'json-loader' },
    {
      loader: '@openzeppelin/solidity-loader',
      options: {
        network: 'development',
        disabled: false,
      }
    },
  ],
}
----

Example of importing Solidity file into JavaScript:
[source,javascript]
----
counterJSON = require('../../contracts/Counter.sol');
----

== Learn More

 * Check out xref:getting-started.adoc[Getting Started] with the Tutorial Starter Kit.
 * Watch Devcon video https://youtu.be/KU6_r3sJ2E4[Delightful Developer Experience] presented by 
Igor Yalovoy.
 * Finally check out xref:dapp.adoc[Building a dapp with Solidity Hot Loader].
